class Journal < ApplicationRecord
  belongs_to :user
  belongs_to :actor_user, class_name: 'User', optional: true

  validates :action, presence: true
  validates :changes_json, presence: true
  validates :changed_at, presence: true

  scope :highlighted, -> { where(highlight: true) }
  scope :recent, -> { order(changed_at: :desc) }

  # Actions that should always be highlighted
  HIGHLIGHTED_ACTIONS = %w[
    created
    incident_report_involvement
    membership_status_changed
    activated
    deactivated
    banned
    training_added
    training_removed
    trainer_capability_added
    trainer_capability_removed
    subscription_created
    subscription_cancelled
  ].freeze

  # Fields whose changes should trigger a highlight
  HIGHLIGHTED_FIELDS = %w[
    membership_status
    dues_status
    banned
    deceased
  ].freeze

  # Fields that are sync/system noise — updates touching ONLY these fields are not highlighted
  SYNC_ONLY_FIELDS = %w[
    authentik_id authentik_attributes authentik_dirty last_synced_at
    email full_name username active
    slack_id slack_handle avatar
    paypal_account_id last_payment_date recharge_customer_id recharge_most_recent_payment_date
    payment_type
    _system_note
  ].freeze

  before_save :determine_highlight

  # Create a journal entry for incident report involvement
  def self.record_incident_involvement!(user:, incident_report:, actor: nil)
    create!(
      user: user,
      actor_user: actor,
      action: 'incident_report_involvement',
      changes_json: {
        'incident_report' => {
          'id' => incident_report.id,
          'subject' => incident_report.subject,
          'type' => incident_report.incident_type_display,
          'date' => incident_report.incident_date.to_s
        }
      },
      changed_at: Time.current,
      highlight: true
    )
  end

  private

  def determine_highlight
    # Skip if already explicitly set to true
    return if highlight?

    self.highlight = should_highlight?
  end

  def should_highlight?
    # Check if action is in highlighted list
    if HIGHLIGHTED_ACTIONS.include?(action)
      # For 'created' and 'updated', skip highlight if it looks like a sync operation
      # (no human actor and only sync-related fields changed)
      return !sync_only_change? if action.in?(%w[created updated])

      return true
    end

    # Check if any highlighted fields were changed
    return true if changes_include_highlighted_fields?

    false
  end

  def changes_include_highlighted_fields?
    return false if changes_json.blank?

    changes_json.keys.intersect?(HIGHLIGHTED_FIELDS)
  end

  # Returns true if this journal entry only contains sync/system field changes
  # with no human actor — i.e., it was generated by an automated sync process
  def sync_only_change?
    return false if actor_user_id.present?
    return true if changes_json.blank?

    changed_fields = changes_json.keys
    (changed_fields - SYNC_ONLY_FIELDS).empty?
  end
end
